WITH CTE AS (
    SELECT 
    RIDE_ID,
    date(TO_TIMESTAMP(STARTED_AT)) AS TRIP_START_DT,
    date(TO_TIMESTAMP(ENDED_AT)) AS TRIP_END_DT,
    TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) TRIP_DURATION_SNCDS,
    START_STATIO_ID AS START_STATION_ID,
    END_STATION_ID,
    MEMBER_CSUAL AS MEMEBER_CASUAL
    FROM
    {{ source('demo', 'bike') }}
    WHERE RIDE_ID!='ride_id'
)
select * from cte